<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="11.*-*" />
		<PackageReference Include="OpenTelemetry.Exporter.InMemory" Version="*" />
		<ProjectReference Include="../../src/Infrastructure.ServiceDefaults/Infrastructure.ServiceDefaults.csproj" />
	</ItemGroup>
</Project>
