<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<NorseRef Include="Persistence.EntityFramework" Generator="true">
			<Repo>Urdarbrunnr</Repo>
		</NorseRef>
		<NorseRef Include="Persistence.EntityFramework.PostgreSQL">
			<Repo>Urdarbrunnr</Repo>
		</NorseRef>
		<NorseRef Include="Persistence.EntityFramework.SqlServer">
			<Repo>Urdarbrunnr</Repo>
		</NorseRef>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="11.*-*" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="11.*-*" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="11.*-*" />
		<PackageReference Include="Testcontainers.MsSql" Version="*" />
		<PackageReference Include="Testcontainers.PostgreSql" Version="*" />
		<ProjectReference Include="../../src/Infrastructure.Persistence.EntityFramework/Infrastructure.Persistence.EntityFramework.csproj" />
	</ItemGroup>
</Project>
